---
:development: &defaults
  :adapter: sqlite3
  :database: db/example_development.sqlite3
  :log_stream: STDOUT
  :log_level: 0

:test:
  <<: *defaults
  :database: db/example_test.sqlite3

:production:
  <<: *defaults
  :database: db/example_production.sqlite3
  :log_stream: nil